2025-04-24 15:36:22,440 - INFO - Running command: scrapy crawl dns_products -a max_items=50
2025-04-24 15:36:23,612 - ERROR - Spider failed with return code 1
2025-04-24 15:36:23,612 - ERROR - Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Scripts\scrapy.exe\__main__.py", line 7, in <module>
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\cmdline.py", line 187, in execute
    cmd.crawler_process = CrawlerProcess(settings)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\crawler.py", line 424, in __init__
    super().__init__(settings)
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\crawler.py", line 295, in __init__
    self.spider_loader: SpiderLoader = self._get_spider_loader(settings)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\crawler.py", line 289, in _get_spider_loader
    return cast("SpiderLoader", loader_cls.from_settings(settings.frozencopy()))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\spiderloader.py", line 81, in from_settings
    return cls(settings)
           ^^^^^^^^^^^^^
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\spiderloader.py", line 36, in __init__
    self._load_all_spiders()
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\spiderloader.py", line 65, in _load_all_spiders
    for module in walk_modules(name):
                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lime_\PycharmProjects\UIPC\.venv\Lib\site-packages\scrapy\utils\misc.py", line 98, in walk_modules
    submod = import_module(fullpath)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lime_\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\lime_\PycharmProjects\UIPC\app\utils\DNS_scrapy\DNS\spiders\dns_products.py", line 10, in <module>
    from ..items import DnsProductItem
ImportError: cannot import name 'DnsProductItem' from 'DNS.items' (C:\Users\lime_\PycharmProjects\UIPC\app\utils\DNS_scrapy\DNS\items.py)

2025-04-24 15:40:05,319 - INFO - Running command: scrapy crawl dns_products -a category=videokarty -a max_items=5
2025-04-24 16:07:47,370 - INFO - Running command: scrapy crawl dns_products -a max_items=50
2025-04-24 16:09:42,978 - INFO - Running command: scrapy crawl dns_products -a max_items=50
2025-04-24 16:12:27,293 - INFO - Running command: scrapy crawl dns_products -a max_items=50
